#pragma once

#include "Camera/CameraComponent.h"
// #include "Actor/VRSSMotionController.h"
#include "GameFramework/Character.h"

#include "VRCharacter.generated.h"

class AVRSSMotionController;

/**
 * VR pawn which the user controls that is also responsible for some interaction of the user with the underlying systems.
 */
UCLASS()
class VRSMOKEVIS_API AVRCharacter : public APawn
{
	GENERATED_BODY()
public:
	/** Default constructor */
	AVRCharacter();

	/** Root component to attach everything to */
	UPROPERTY(VisibleAnywhere)
	USceneComponent* HMDScene;

	/** VR Camera component */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UCameraComponent* VRCamera;

	/** Blueprint class of the controller for both hands */
	UPROPERTY(EditAnywhere)
	TSubclassOf<AVRSSMotionController> PlayerControllerClass;
	
	/** Controller spawned for the left hand */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	AVRSSMotionController* LeftController;

	/** Controller spawned for the right hand */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	AVRSSMotionController* RightController;

	/** Called when the game starts or when spawned */
	virtual void BeginPlay() override;

	UPROPERTY(EditAnywhere)
	TSubclassOf<class USimLoadingPromptUserWidget> SimLoadingPromptUserWidgetClass;
	
	UPROPERTY(EditAnywhere)
	TSubclassOf<class AVRUI> VRUIClass;

protected:	
	/** Pause the simulation and propagate the pause to all assets  */
	UFUNCTION()
	void TogglePauseSimulation();
	/** Forward the simulation time by a set amount of time */
	UFUNCTION()
	void FastForwardSimulation();
	/** Rewind the simulation time by a set amount of time */
	UFUNCTION()
	void RewindSimulation();

	/** Completely show or hide the HUD */
	UFUNCTION()
	void ToggleHUDVisibility();

	/** Opens the prompt for loading a simulation where the user enters the path to the .smv file generated by FDS */
	UFUNCTION()
	void ToggleSimLoadingPrompt();

	/** Opens the HUD in VR mode on one controller */
	UFUNCTION()
	void VRMenuToggle(const bool IsRightHand);
	
	UPROPERTY(Transient)
	class USimLoadingPromptUserWidget* SimLoadingPromptUserWidget;
	
	UPROPERTY()
	class AVRUI* VRUI;
};
