#pragma once

#include "Camera/CameraComponent.h"
#include "Actor/VRSSPlayerController.h"
#include "GameFramework/Character.h"

#include "VRCharacter.generated.h"

class AVRSSPlayerController;

/**
 * VR pawn which the user controls that is also responsible for some interaction of the user with the underlying systems.
 */
UCLASS()
class VRSMOKEVIS_API AVRCharacter : public APawn
{
	GENERATED_BODY()
public:
	/** Default constructor */
	AVRCharacter();

	/** Root component to attach everything to */
	UPROPERTY(VisibleAnywhere)
	USceneComponent* HMDScene;

	/** VR Camera component */
	UPROPERTY(VisibleAnywhere)
	UCameraComponent* VRCamera;

	/** Blueprint class of the controller for both hands */
	UPROPERTY(EditAnywhere)
	TSubclassOf<AVRSSPlayerController> PlayerControllerClass;
	
	/** Controller spawned for the left hand */
	UPROPERTY(VisibleAnywhere)
	AVRSSPlayerController* LeftController;

	/** Controller spawned for the right hand */
	UPROPERTY(VisibleAnywhere)
	AVRSSPlayerController* RightController;

	/** Called when the game starts or when spawned */
	virtual void BeginPlay() override;

	UPROPERTY(EditAnywhere)
	TSubclassOf<class USimLoadingPromptUserWidget> SimLoadingPromptUserWidgetClass;

protected:
	/** Pause the simulation and propagate the pause to all assets  */
	UFUNCTION()
	void TogglePauseSimulation();
	/** Forward the simulation time by a set amount of time */
	UFUNCTION()
	void FastForwardSimulation();
	/** Rewind the simulation time by a set amount of time */
	UFUNCTION()
	void RewindSimulation();

	/** Completely show or hide the HUD */
	UFUNCTION()
	void ToggleHUDVisibility();

	/** Opens the prompt for loading a simulation where the user enters the path to the .smv file generated by FDS */
	UFUNCTION()
	void ShowSimLoadingPrompt();
};
